use_frameworks!

platform :ios, '8.0'

target 'Polaris_Example' do
  pod 'Polaris', :path => '../'

  target 'Polaris_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
